export const LOADING = 'LOADING'
export const SUCCESS = 'SUCCESS'
export const ERROR = 'ERROR'

export const LOAD_NEXT_GIFT = 'LOAD_NEXT_GIFT'
export const LOAD_NEXT_GIFT_LOADING = 'LOAD_NEXT_GIFT_LOADING'
export const LOAD_NEXT_GIFT_SUCCESS = 'LOAD_NEXT_GIFT_SUCCESS'
export const LOAD_NEXT_GIFT_ERROR = 'LOAD_NEXT_GIFT_ERROR'

export const ADD_TO_HISTORY = 'ADD_TO_HISTORY'
export const REMOVE_FROM_HISTORY = 'REMOVE_FROM_HISTORY'

export const ADD_TO_FAVOURITE = 'ADD_TO_FAVOURITE'
export const REMOVE_FROM_FAVOURITE = 'REMOVE_FROM_FAVOURITE'

export const SEND_NAME = 'SEND_NAME'
export const SEND_NAME_LOADING = 'SEND_NAME_LOADING'
export const SEND_NAME_SUCCESS = 'SEND_NAME_SUCCESS'
export const SEND_NAME_ERROR = 'SEND_NAME_ERROR'

export const LIKE_ITEM = 'LIKE_ITEM'
export const DISLIKE_ITEM = 'DISLIKE_ITEM'
export const NORMAS = 'NORMAS'
